name = "estoque-calcados"
compatibility_date = "2024-10-01"

# Para `wrangler pages dev` com D1 local
[[d1_databases]]
binding = "DB"
database_name = "estoque"
database_id = "local-estoque"

[[kv_namespaces]]
binding = "KV_BINDING"
id = "6f3e5f7fc7864b64accffb8c04e7dbe3"
preview_id = "6f3e5f7fc7864b64accffb8c04e7dbe3"
