name = "estoque-calcados"
compatibility_date = "2024-10-01"

[[d1_databases]]
binding = "DB"
database_name = "estoque"
database_id = "bd409c97-96fb-42d1-a1f3-03da8d5bdd71"

[[kv_namespaces]]
binding = "KV_BINDING"
id = "6f3e5f7fc7864b64accffb8c04e7dbe3"
preview_id = "6f3e5f7fc7864b64accffb8c04e7dbe3"
